In [1]:
import numpy as np

In [46]:
import pandas as pd

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [6]:
list(np.linspace(1,5,20,retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [7]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [8]:
np.linspace(1,4,7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [18]:
np.zeros((3,2,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
np.ones((2,3,3))*5

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [30]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
a=np.eye(7)

In [40]:
a.shape

(7, 7)

In [41]:
a.size

49

In [43]:
a1=np.random.randn(3,4)

In [44]:
a1

array([[ 1.20394705, -0.53360879,  0.06077044, -0.51102666],
       [-1.49249128, -1.21479638,  1.91340047,  0.24686107],
       [-0.11776149, -0.65398318,  0.77313097,  0.57885713]])

In [45]:
a1[1][1]

-1.2147963775569348

In [47]:
pd.DataFrame(a1)

0         1         2         3
0  1.203947 -0.533609  0.060770 -0.511027
1 -1.492491 -1.214796  1.913400  0.246861
2 -0.117761 -0.653983  0.773131  0.578857

In [49]:
a1[0:2,0:2]

array([[ 1.20394705, -0.53360879],
       [-1.49249128, -1.21479638]])

In [50]:
a1[[1,2],3]

array([0.24686107, 0.57885713])

In [52]:
m1=np.random.randint(1,3,(3,3))

In [53]:
m1

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [54]:
m2=np.random.randint(2,4,(3,3))

In [55]:
m2

array([[3, 2, 3],
       [3, 2, 3],
       [3, 3, 2]])

In [56]:
m1*m2

array([[6, 4, 3],
       [3, 2, 6],
       [3, 6, 2]])

In [57]:
m1@m2

array([[15, 11, 14],
       [12, 10, 10],
       [12,  9, 11]])

In [58]:
a1

array([[ 1.20394705, -0.53360879,  0.06077044, -0.51102666],
       [-1.49249128, -1.21479638,  1.91340047,  0.24686107],
       [-0.11776149, -0.65398318,  0.77313097,  0.57885713]])

In [59]:
a1[1,2]

array([1.91340047, 0.77313097])

In [62]:
a1[0][2]

0.060770443910241924

In [75]:
a1[1:,2:]

array([[1.91340047, 0.24686107],
       [0.77313097, 0.57885713]])

In [69]:
pow(m1,4)

array([[16, 16,  1],
       [ 1,  1, 16],
       [ 1, 16,  1]], dtype=int32)

In [70]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [71]:
np.log(m1)

array([[0.69314718, 0.69314718, 0.        ],
       [0.        , 0.        , 0.69314718],
       [0.        , 0.69314718, 0.        ]])

In [72]:
np.log10(m1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.     ]])

In [73]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [74]:
m1**2

array([[4, 4, 1],
       [1, 1, 4],
       [1, 4, 1]], dtype=int32)

In [76]:
a1

array([[ 1.20394705, -0.53360879,  0.06077044, -0.51102666],
       [-1.49249128, -1.21479638,  1.91340047,  0.24686107],
       [-0.11776149, -0.65398318,  0.77313097,  0.57885713]])

In [77]:
a1[0:2,1:3]

array([[-0.53360879,  0.06077044],
       [-1.21479638,  1.91340047]])

In [1]:
pip install cufflinks

Note: you may need to restart the kernel to use updated packages.


In [1]:
import cufflinks as cf
import numpy as np 
import pandas as pd
import seaborn as sns

In [2]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [3]:
df

A         B         C
0   0.783967 -2.202072  1.708573
1  -0.058981  0.064575  0.019960
2  -0.467716 -0.449176  0.269765
3   1.647638 -0.097326 -1.159923
4  -0.121367 -0.866296 -1.231128
..       ...       ...       ...
95 -0.384348  0.216627 -0.042448
96  0.495419  0.705842  0.410860
97  1.147859 -0.509002  0.596643
98  1.520185 -0.130374  0.278008
99 -1.002676 -0.994496  1.060757

[100 rows x 3 columns]

In [4]:
pip install chart_studio

Note: you may need to restart the kernel to use updated packages.


In [7]:
df[["A"]].iplot()

In [5]:
from plotly.offline import iplot
import cufflinks as cf

In [6]:
cf.go_offline()