In [4]:
import pandas as pd

In [30]:
d1 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,9,10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,22,23,24]
}

In [31]:
df1=pd.DataFrame(d1)

In [32]:
df1


key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [33]:
d2 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"Kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"Ineuron","Pwskills",24]
}

In [34]:
df2=pd.DataFrame(d2)

In [35]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  Kumar    15        21
3     4     10    16   Ineuron
4     5     11    17  Pwskills
5  sudh     12    18        24

In [8]:
pd.merge(df1,df2,how='inner',on='key1')

key1  key2_x  key3_x  key4_x key2_y  key3_y    key4_y
0     1       7      13      19      7      13        19
1     2       8      14      20      8      14        20
2     3       9      15      21  Kumar      15        21
3     4      10      16      22     10      16   Ineuron
4     5      11      17      23     11      17  Pwskills
5  sudh      12      18      24     12      18        24

In [9]:
pd.merge(df1,df2,how='inner',on='key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7      13
1      2       8      14   20      2      8      14
2      3       9      15   21      3  Kumar      15
3   sudh      12      18   24   sudh     12      18

In [10]:
pd.merge(df1,df2,how='left',on='key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7    13.0
1      2       8      14   20      2      8    14.0
2      3       9      15   21      3  Kumar    15.0
3      4      10      16   22    NaN    NaN     NaN
4      5      11      17   23    NaN    NaN     NaN
5   sudh      12      18   24   sudh     12    18.0

In [11]:
pd.merge(df1,df2,how='right',on='key4')

key1_x  key2_x  key3_x      key4 key1_y key2_y  key3_y
0      1     7.0    13.0      19.0      1      7      13
1      2     8.0    14.0      20.0      2      8      14
2      3     9.0    15.0      21.0      3  Kumar      15
3    NaN     NaN     NaN   Ineuron      4     10      16
4    NaN     NaN     NaN  Pwskills      5     11      17
5   sudh    12.0    18.0      24.0   sudh     12      18

In [12]:
pd.merge(df1,df2,how='outer',on='key4')

key1_x  key2_x  key3_x      key4 key1_y key2_y  key3_y
0      1     7.0    13.0      19.0      1      7    13.0
1      2     8.0    14.0      20.0      2      8    14.0
2      3     9.0    15.0      21.0      3  Kumar    15.0
3      4    10.0    16.0      22.0    NaN    NaN     NaN
4      5    11.0    17.0      23.0    NaN    NaN     NaN
5   sudh    12.0    18.0      24.0   sudh     12    18.0
6    NaN     NaN     NaN   Ineuron      4     10    16.0
7    NaN     NaN     NaN  Pwskills      5     11    17.0

In [13]:
pd.merge(df1,df2,how='outer',on=['key1','key4'])

key1  key2_x  key3_x      key4 key2_y  key3_y
0     1     7.0    13.0      19.0      7    13.0
1     2     8.0    14.0      20.0      8    14.0
2     3     9.0    15.0      21.0  Kumar    15.0
3     4    10.0    16.0      22.0    NaN     NaN
4     5    11.0    17.0      23.0    NaN     NaN
5  sudh    12.0    18.0      24.0     12    18.0
6     4     NaN     NaN   Ineuron     10    16.0
7     5     NaN     NaN  Pwskills     11    17.0

In [14]:
d11 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}

In [15]:
d22 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"Kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"Ineuron","Pwskills",24]
}

In [16]:
df11=pd.DataFrame(d11)

In [17]:
df22=pd.DataFrame(d22)

In [18]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [19]:
df22

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  Kumar    15        21
3     4     10    16   Ineuron
4     5     11    17  Pwskills
5  sudh     12    18        24

In [20]:
pd.merge(df11,df22,how='left',left_on='a',right_on='key1')

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  Kumar    15        21
3     4  10  16  22     4     10    16   Ineuron
4     5  11  17  23     5     11    17  Pwskills
5  sudh  12  18  24  sudh     12    18        24

In [21]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [22]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  Kumar    15        21
3     4     10    16   Ineuron
4     5     11    17  Pwskills
5  sudh     12    18        24

## Join Ops

In [5]:
d10 = {'key11':[1,2,3,4,5,"sudh"],
      'key21' : [7,8,9,10,11,12],
      'key31':[13,14,15,16,17,18],
      'key41':[19,20,21,22,23,24]
}

In [6]:
d20 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"Kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"Ineuron","Pwskills",24]
}

In [7]:
df10=pd.DataFrame(d10,index=[1,2,3,4,5,6])

In [17]:
df20=pd.DataFrame(d20,index=[1,2,3,4,5,'sudh'])

In [23]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [24]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  Kumar    15        21
4        4     10    16   Ineuron
5        5     11    17  Pwskills
sudh  sudh     12    18        24

In [18]:
df10.join(df20,how='right')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7    13        19
2        2    8.0   14.0   20.0     2      8    14        20
3        3    9.0   15.0   21.0     3  Kumar    15        21
4        4   10.0   16.0   22.0     4     10    16   Ineuron
5        5   11.0   17.0   23.0     5     11    17  Pwskills
sudh   NaN    NaN    NaN    NaN  sudh     12    18        24

In [19]:
df10.join(df20)

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7  13.0        19
2     2      8     14     20    2      8  14.0        20
3     3      9     15     21    3  Kumar  15.0        21
4     4     10     16     22    4     10  16.0   Ineuron
5     5     11     17     23    5     11  17.0  Pwskills
6  sudh     12     18     24  NaN    NaN   NaN       NaN

In [20]:
df10.join(df20,how='left')

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7  13.0        19
2     2      8     14     20    2      8  14.0        20
3     3      9     15     21    3  Kumar  15.0        21
4     4     10     16     22    4     10  16.0   Ineuron
5     5     11     17     23    5     11  17.0  Pwskills
6  sudh     12     18     24  NaN    NaN   NaN       NaN

In [21]:
df10.join(df20,how='inner')

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7    13        19
2     2      8     14     20    2      8    14        20
3     3      9     15     21    3  Kumar    15        21
4     4     10     16     22    4     10    16   Ineuron
5     5     11     17     23    5     11    17  Pwskills

In [22]:
df10.join(df20,how='outer')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7  13.0        19
2        2    8.0   14.0   20.0     2      8  14.0        20
3        3    9.0   15.0   21.0     3  Kumar  15.0        21
4        4   10.0   16.0   22.0     4     10  16.0   Ineuron
5        5   11.0   17.0   23.0     5     11  17.0  Pwskills
6     sudh   12.0   18.0   24.0   NaN    NaN   NaN       NaN
sudh   NaN    NaN    NaN    NaN  sudh     12  18.0        24

In [26]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [27]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  Kumar    15        21
4        4     10    16   Ineuron
5        5     11    17  Pwskills
sudh  sudh     12    18        24

In [28]:
pd.concat([df10,df20],axis=0)

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0   NaN    NaN   NaN       NaN
2        2    8.0   14.0   20.0   NaN    NaN   NaN       NaN
3        3    9.0   15.0   21.0   NaN    NaN   NaN       NaN
4        4   10.0   16.0   22.0   NaN    NaN   NaN       NaN
5        5   11.0   17.0   23.0   NaN    NaN   NaN       NaN
6     sudh   12.0   18.0   24.0   NaN    NaN   NaN       NaN
1      NaN    NaN    NaN    NaN     1      7  13.0        19
2      NaN    NaN    NaN    NaN     2      8  14.0        20
3      NaN    NaN    NaN    NaN     3  Kumar  15.0        21
4      NaN    NaN    NaN    NaN     4     10  16.0   Ineuron
5      NaN    NaN    NaN    NaN     5     11  17.0  Pwskills
sudh   NaN    NaN    NaN    NaN  sudh     12  18.0        24

In [36]:
pd.concat([df1,df2],axis=0)

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3      9    15        21
3     4     10    16        22
4     5     11    17        23
5  sudh     12    18        24
0     1      7    13        19
1     2      8    14        20
2     3  Kumar    15        21
3     4     10    16   Ineuron
4     5     11    17  Pwskills
5  sudh     12    18        24

In [37]:
pd.concat([df1,df2],axis=1)

key1 key2  key3 key4  key1   key2  key3      key4
0     1    7    13   19     1      7    13        19
1     2    8    14   20     2      8    14        20
2     3    9    15   21     3  Kumar    15        21
3     4   10    16   22     4     10    16   Ineuron
4     5   11    17   23     5     11    17  Pwskills
5  sudh   12    18   24  sudh     12    18        24

In [38]:
import numpy as np

In [39]:
l=[1,2,3,4,4]

In [41]:
a=np.array(l)

In [42]:
type(a)

numpy.ndarray

In [43]:
a1=np.array([[1,2,3],[3,4,5]])

In [44]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [45]:
a32=np.array([[[1,2,3],[4,5,6]]])

In [46]:
a32

array([[[1, 2, 3],
        [4, 5, 6]]])

In [47]:
a.ndim

1

In [48]:
a1.ndim

2

In [49]:
a32.ndim

3

In [50]:
a3=np.array([[[1,2,3],[4,5,6]],
             [[1,2,3],[4,5,6]],
             [[1,2,3],[4,5,6]]])

In [51]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [52]:
a3.ndim

3

In [54]:
type(a3)

numpy.ndarray

In [55]:
l=[1,2,3,4]

In [60]:
a=np.asarray(l)

In [61]:
a

array([1, 2, 3, 4])

In [57]:
m=np.matrix(l)

Matrix is always by default in two dimensions.

In [58]:
m

matrix([[1, 2, 3, 4]])

In [62]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [63]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [64]:
a1=a

In [65]:
a

array([1, 2, 3, 4])

In [67]:
a[0]=10

In [68]:
a

array([10,  2,  3,  4])

In [69]:
a1=a

In [70]:
a1

array([10,  2,  3,  4])

In [72]:
a1[3]=50

In [73]:
a1

array([10,  2,  3, 50])

In [74]:
a2=np.copy(a)

In [75]:
a2

array([10,  2,  3, 50])

In [77]:
a2[2]=30

In [78]:
a2

array([10,  2, 30, 50])

In [79]:
a

array([10,  2,  3, 50])

## Numpy Functions

In this inbuilt function we have to input function ,shape.

In [80]:
np.fromfunction(lambda i,j : i==j , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [84]:
np.random.rand(2,3)

array([[0.67133414, 0.94949758, 0.7341947 ],
       [0.62356977, 0.97301744, 0.43316848]])

In [86]:
np.random.rand(2,3,4)

array([[[0.62619927, 0.15306606, 0.3068854 , 0.20249479],
        [0.31088291, 0.91234913, 0.5305893 , 0.91003955],
        [0.9791481 , 0.84258014, 0.30199419, 0.17187067]],

       [[0.28824635, 0.77379232, 0.15709233, 0.70688771],
        [0.11438078, 0.69208312, 0.35466895, 0.73123553],
        [0.85503634, 0.5880988 , 0.41538877, 0.76210275]]])

In [87]:
np.random.rand(2,2,3,2)

array([[[[0.72641167, 0.26443314],
         [0.2855779 , 0.49936294],
         [0.08370026, 0.51098944]],

        [[0.15832818, 0.52713869],
         [0.82497138, 0.27216054],
         [0.00797861, 0.26390383]]],


       [[[0.40802367, 0.13174274],
         [0.65117854, 0.23187803],
         [0.92555466, 0.83988663]],

        [[0.96322225, 0.60200631],
         [0.72160395, 0.94843033],
         [0.4990426 , 0.48032567]]]])

In [88]:
np.random.rand(3,4,4)

array([[[0.16804309, 0.10955557, 0.18557702, 0.02906942],
        [0.14317839, 0.56647338, 0.36621911, 0.24496946],
        [0.03546074, 0.39766084, 0.12367086, 0.31448408],
        [0.84837903, 0.12528658, 0.50946763, 0.36599823]],

       [[0.45878889, 0.9014117 , 0.91977537, 0.45465206],
        [0.56716142, 0.96327059, 0.22163131, 0.3062605 ],
        [0.06619479, 0.11274675, 0.7802604 , 0.52093836],
        [0.4561305 , 0.21097676, 0.20319429, 0.29421884]],

       [[0.2035405 , 0.82924081, 0.82342271, 0.94393444],
        [0.98539013, 0.35472955, 0.41840072, 0.2700976 ],
        [0.76725462, 0.48525271, 0.19265957, 0.43479017],
        [0.89281997, 0.75159642, 0.4948777 , 0.87426173]]])

Randn-Function : Mean=0 , Std=1

In [93]:
np.random.randn(3,4,4)

array([[[ 1.69440438,  1.07649179,  0.07197026, -0.34465263],
        [-1.32808604,  2.92803418, -0.03647026, -0.35275732],
        [-1.57278999,  0.38543533, -0.44331493, -0.3832238 ],
        [ 1.55411604, -0.45745034, -0.60911608, -1.24715912]],

       [[ 0.51230159, -0.78933709,  0.04502103,  0.55480328],
        [-1.26600319, -0.23982732, -1.46329465, -1.59037678],
        [-0.48734918, -0.64324664,  0.32119552,  0.22066518],
        [-0.85814722, -0.40762975, -0.97617208, -0.14391473]],

       [[ 0.01492773,  1.47749222, -0.23147702, -0.1979306 ],
        [ 1.20030625,  0.52680225,  0.26744094,  1.08000531],
        [-0.2360325 ,  0.42158792, -1.66606317, -0.25465021],
        [-1.0493781 , -0.74114578, -0.32519989,  0.88018454]]])

In [92]:
d=np.random.randn(3,4)

In [99]:
np.random.randint(0,10,(4,4,2))

array([[[6, 9],
        [6, 5],
        [4, 6],
        [1, 8]],

       [[3, 7],
        [1, 4],
        [1, 0],
        [6, 4]],

       [[7, 8],
        [2, 8],
        [5, 1],
        [6, 0]],

       [[1, 5],
        [1, 9],
        [3, 7],
        [1, 2]]])

In [100]:
d1=np.random.randint(0,10,(4,4,2))

In [96]:
pd.DataFrame(d)

0         1         2         3
0 -1.020065 -1.094843  2.094332  0.293287
1 -0.710172 -0.890874 -2.123834 -1.426156
2 -1.591375  1.078490  1.484881 -0.329764

In [98]:
try:
    pd.DataFrame(d1)
except Exception as e:
    print(e)

Must pass 2-d input. shape=(4, 4, 2)


## NumPy Reshape Function

In [112]:
d1.reshape(16,2)

array([[7, 2],
       [8, 9],
       [2, 9],
       [7, 8],
       [4, 1],
       [6, 1],
       [3, 1],
       [6, 0],
       [6, 1],
       [5, 4],
       [9, 3],
       [6, 6],
       [8, 7],
       [4, 5],
       [3, 1],
       [9, 4]])

In [110]:
d5=d1.reshape(16,2)

In [102]:
d1.reshape(8,4)

array([[7, 2, 8, 9],
       [2, 9, 7, 8],
       [4, 1, 6, 1],
       [3, 1, 6, 0],
       [6, 1, 5, 4],
       [9, 3, 6, 6],
       [8, 7, 4, 5],
       [3, 1, 9, 4]])

Numpy Negative Placeholder 

In [111]:
d1.reshape(8,-16)

array([[7, 2, 8, 9],
       [2, 9, 7, 8],
       [4, 1, 6, 1],
       [3, 1, 6, 0],
       [6, 1, 5, 4],
       [9, 3, 6, 6],
       [8, 7, 4, 5],
       [3, 1, 9, 4]])

In [109]:
d4=d1.reshape(8,-16)

In [104]:
d1.reshape(2,-1)

array([[7, 2, 8, 9, 2, 9, 7, 8, 4, 1, 6, 1, 3, 1, 6, 0],
       [6, 1, 5, 4, 9, 3, 6, 6, 8, 7, 4, 5, 3, 1, 9, 4]])

In [107]:
d3=d1.reshape(32,-1)

In [108]:
pd.DataFrame(d3)

0
0   7
1   2
2   8
3   9
4   2
5   9
6   7
7   8
8   4
9   1
10  6
11  1
12  3
13  1
14  6
15  0
16  6
17  1
18  5
19  4
20  9
21  3
22  6
23  6
24  8
25  7
26  4
27  5
28  3
29  1
30  9
31  4

In [114]:
pd.DataFrame(d4)

0  1  2  3
0  7  2  8  9
1  2  9  7  8
2  4  1  6  1
3  3  1  6  0
4  6  1  5  4
5  9  3  6  6
6  8  7  4  5
7  3  1  9  4

In [115]:
pd.DataFrame(d5)

0  1
0   7  2
1   8  9
2   2  9
3   7  8
4   4  1
5   6  1
6   3  1
7   6  0
8   6  1
9   5  4
10  9  3
11  6  6
12  8  7
13  4  5
14  3  1
15  9  4